Foodplaza/urls.py
from django.contrib import admin
from django.contrib.auth import logout
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from Foodapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('addfood/', views.addFood),
    path('showfood/', views.menu),
    path('deletefood/<int:id>', views.Deletefood),
    path('updatefood/<int:id>', views.Updatefood),
    path('signup', views.CreateUser),
    path('showuser', views.showUsers),
    path('login/', views.logins),
    path('index/', views.index),
    path('logout/', views.logouts),
    path('', views.index),
    path('profile/', views.userprofile),
    path('updatecust/', views.editProfile),
    path('addtocart/', views.addcart),
    path('cart', views.showCart),
    path('updatecart/', views.updatecart),
    path('deletecart/<int:id>', views.deleteCart),
    path('addorders/', views.addorders),
    path('showalluser/', views.showallorders),
    path('showorders/', views.showOrders),
    path('graph/', views.graph),
    path('customergraph/', views.cgraph),
    path('categorygraph/', views.categorygraph),
    path('ordergraph/', views.ordergraph),
    path('ccountgraph/', views.ccountgraph)


]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Foodapp/models.py
from django.conf.urls.static import static
from django.db import models
from django.contrib.auth.models import User, Group
from django.db.models.deletion import CASCADE
from django.forms.widgets import NumberInput
import datetime

# Create your models here.


class Food(models.Model):
    category = [('veg', 'vegitarian'), ('Non-veg', 'Non-vegitarian')]
    name = models.CharField(max_length=50)
    price = models.FloatField()
    quantity = models.IntegerField()
    types = models.CharField(max_length=30)
    category = models.CharField(choices=category, max_length=30)
    image = models.ImageField(upload_to='media', default='')

    class Meta:
        db_table = 'foodDB'


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    location = models.CharField(max_length=50)
    number = models.CharField(max_length=10)

    class Meta:
        db_table = 'UserProfile'


customer, created = Group.objects.get_or_create(
    name='Customer')  # name=Customer is shown into browser
admin, createds = Group.objects.get_or_create(name='admin')
# line number 30 and 31 is used to create groups in our admin panel of django in browser
#print(customer, admin, created, createds)


class Cart(models.Model):
    currentuser = models.ForeignKey(User, on_delete=models.CASCADE)
    itemquantity = models.IntegerField(default=1)
    fid = models.ForeignKey(Food, on_delete=models.CASCADE)
    total = models.FloatField()

    class Meta:
        db_table = 'cart'


class OrderSummery1(models.Model):
    dt = datetime.datetime.now().strftime('%Y-%m-%d %H:%M')
    statusChoices = [('Pending', 'Pending'), ('Delivered',
                                              'Delivered'), ('Cancel', 'Cancel')]
    date = models.CharField(default=str(dt), blank=True, max_length=25)
    totalamount = models.FloatField()
    customer = models.ForeignKey(User, on_delete=models.CASCADE)
    status = models.CharField(
        max_length=19, choices=statusChoices, default='Pending')

    class Meta:
        db_table = "ordersummery"


class Orders(models.Model):
    ordersobj = models.ForeignKey(OrderSummery1, on_delete=models.CASCADE)
    food = models.ForeignKey(Food, on_delete=models.CASCADE)
    total = models.IntegerField()
    foodQuant = models.IntegerField()

    class Meta:
        db_table = 'Orders'

Foodapp/forms.py
from django.forms import fields, widgets
from Foodapp import models
from Foodapp.models import Food, UserProfile
from django import forms
from django.contrib.auth.models import User


class Foodform(forms.ModelForm):
    category = [('veg', 'vegitarian'), ('Non-veg', 'Non-vegetarian')]
    name = forms.CharField(widget=forms.TextInput(
        attrs={'id': 'ni', 'class': 'c1'}))
    price = forms.FloatField(widget=forms.NumberInput())
    quantity = forms.IntegerField(widget=forms.TextInput())
    types = forms.CharField(widget=forms.TextInput())
    category = forms.ChoiceField(choices=category)
    image = forms.ImageField()

    class Meta:
        model = Food
        fields = '__all__'


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'password', 'email', 'first_name', 'last_name']


class UserProfileForm(forms.ModelForm):
    role = [('customersss', 'CUSTOMER'), ('adminsss', 'ADMIN')]
    Role = forms.ChoiceField(
        choices=role, initial='Customer', widget=forms.RadioSelect)

    class Meta:
        model = UserProfile
        fields = ['location', 'number']

Foodapp/views.py
from django.db.models.aggregates import Count
from django.forms.forms import Form
from django.http import request
from django.shortcuts import redirect, render
from . import forms
from django.http import JsonResponse
from .models import Food, UserProfile,  Cart, OrderSummery1, Orders
from django.contrib.auth.models import Group, User
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate, login, logout
from django.db.models import Sum, Count
import numpy as np
import pandas as pd
from pandas.core.frame import DataFrame
import matplotlib.pyplot as plt
from numpy.core.fromnumeric import size
from django_pandas.io import read_frame
import seaborn as sns
# Create your views here.


def index(req):
    count = Cart.objects.filter(currentuser=req.user).count()
    return render(req, 'Foodapp/index.html', {'count': count})


def addFood(req):
    form = forms.Foodform()
    print("/////", form)
    if req.method == "POST":
        form = forms.Foodform(req.POST, req.FILES)
        if form.is_valid():
            print("//////", form)
            form.save(commit=True)
    #count = Cart.objects.filter(currentuser=req.user).count()
    return render(req, 'Foodapp/addfood.html', {'form': form})


def menu(request):
    food = Food.objects.all()
    cartid = Cart.objects.filter(currentuser=request.user).values_list('fid')
    print('CART ID ', cartid)
    cartdata = []
    for i in cartid:
        cartdata.append(i[0])
    print('#$#$#$#$#$#$', cartdata)
    count = Cart.objects.filter(currentuser=request.user).count()
    return render(request, 'Foodapp/menu.html', {'food': food, 'cartdata': cartdata, 'count': count})


def Deletefood(req, id):
    food = Food.objects.filter(id=id)
    food.delete()
    #count = Cart.objects.filter(currentuser=req.user).count()
    return redirect('/showfood')


# @permission_required('Foodapp.chage_food', login_url='/loginUser')
def Updatefood(req, id):
    food = Food.objects.get(id=id)
    print(food)
    form = forms.Foodform()
    print('####', form)

    if req.method == "POST":
        form = forms.Foodform(req.POST, req.FILES, instance=food)
        if form.is_valid():
            print("/////", form)
            form.save(commit=True)
            return redirect('/showfood')
    count = Cart.objects.filter(currentuser=req.user).count()
    return render(req, 'Foodapp/updatefood.html', {'food': food, 'count': count})


def CreateUser(req):
    form = forms.UserForm()
    form1 = forms.UserProfileForm()
    if req.method == 'POST':
        form = forms.UserForm(req.POST)
        form1 = forms.UserProfileForm(req.POST)
        role = req.POST['Role']
        print(role)
        if form.is_valid() and form1.is_valid():
            user = form.save(commit=True)
            Userprofile = form1.save(commit=False)
            user.set_password(user.password)
            user.save()
            Userprofile.user = user
            Userprofile.save()
            if role == 'customersss':
                print('printing customer', role)
                cust = Group.objects.get(name='Customer')
                user.groups.add(cust)
            elif role == 'adminsss':
                print('printing admin', role)
                admin = Group.objects.get(name='admin')
                user.groups.add(admin)
            return redirect('/login')
    count = Cart.objects.filter(currentuser=req.user).count()
    return render(req, 'Foodapp/register.html', {'form': form, 'form1': form1, 'count': count})


def showUsers(req):
    data = UserProfile.objects.all()
    count = Cart.objects.filter(currentuser=req.user).count()
    return render(req, 'Foodapp/customer.html', {'data': data, 'count': count})


def logins(request):
    form = AuthenticationForm()
    if request.method == 'POST':
        username = request. POST['username']
        password = request. POST['password']
        user = authenticate(username=username, password=password)
        print(username, user)

        if user != None:
            print(user)
            login(request, user)
            return redirect('/index')

        else:
            msg = 'username or password is worng'
            print('hello')
            return render(request, 'Foodapp/login.html', {'form': form, 'msg': msg})
    #count = Cart.objects.filter(currentuser=request.user).count()
    return render(request, 'Foodapp/login.html', {'form': form})


def logouts(req):
    print('logout...........')
    logout(req)
    return render(req, 'Foodapp/index.html')


def userprofile(req):
    currentuser = req.user
    data1 = UserProfile.objects.get(user=currentuser)
    # User is built in model class auth application
    data2 = User.objects.get(username=currentuser)
    qset = Group.objects.get(user=currentuser)
    role = qset.name
    count = Cart.objects.filter(currentuser=req.user).count()
    return render(req, 'Foodapp/profile.html', {'data1': data1, 'data2': data2, 'role': role, 'count': count})


def updatecart(request):
    quantity = request.POST.get('q')
    price = request.POST.get('p')
    print('PRICE/////////', price)

    cartid = request.POST.get('id')
    amount = int(quantity)*float(price)
    print('AMOUNT######', amount)
    Cart.objects.filter(id=cartid).update(itemquantity=quantity, total=amount)
    bill = Cart.objects.aggregate(Sum('total'))
    print(bill)
    totalam = bill['total__sum']
    count = Cart.objects.filter(currentuser=request.user).count()
    return JsonResponse({'status': 'true', 'bill': totalam, 'amount': amount, 'count': count})


def editProfile(req):
    print('inside editprofile')
    currentUser = req.user
    print('/////////////', currentUser)
    data1 = UserProfile.objects.get(user=currentUser)
    data2 = User.objects.get(username=currentUser)
    #profile = forms.UserProfileForm(data1)
    #form = forms.UserForm(data2)

    if req.method == "POST":
        profile = forms.UserProfileForm(req.POST, instance=data1)
        form = forms.UserForm(req.POST, instance=data2)
        if form.is_valid() and profile.is_valid():
            user = form.save(commit=True)
            profile = profile.save(commit=False)
            profile.user = user
            profile.save()
            form.save()
            return redirect('/showfood')
    count = Cart.objects.filter(currentuser=req.user).count()
    return render(req, 'Foodapp/index.html', {'count': count})


def addcart(req):
    print('ADD TO CAR ????????????????????????', req.GET)
    fid = req.GET['foodid']
    print(fid)
    #price = req.GET.get('price')
    # print(price)
    foodobj = Food.objects.get(id=fid)
    price = foodobj.price
    cuser = req.user
    Cart(currentuser=cuser, fid=foodobj, total=price).save()
    print(price, foodobj, cuser)
    print(req)
    count = Cart.objects.filter(currentuser=req.user).count()
    return render(req, 'Foodapp/menu.html', {'count': count})


def showCart(req):
    user = req.user
    data = Cart.objects.filter(currentuser=user)
    print(data)
    # global totalam
    # totalam = 0
    count = Cart.objects.filter(currentuser=req.user).count()
    return render(req, 'Foodapp/cart.html', {'cart': data, 'count': count})


def deleteCart(req, id):
    Cartobj = Cart.objects.get(id=id)
    print('/////////////////////////////////', Cartobj)
    Cartobj.delete()
    count = Cart.objects.filter(currentuser=req.user).count()
    return redirect('/cart', {'count': count})


def addorders(req):
    try:
        amount = req.POST.get('totalbill')
        print('AMOUNT  ', amount)
        user = req.user
        ordsumobject = OrderSummery1.objects.create(
            totalamount=amount, customer=user)
        ordsumobject.save()
        cart = list(Cart.objects.filter(currentuser=user))
        print(cart)
        for c in cart:
            ordobj = Orders(ordersobj=ordsumobject, food=c.fid,
                            total=c.total, foodQuant=c.itemquantity)
            print('##############', ordobj)
            ordobj.save()
            c.delete()
        count = Cart.objects.filter(currentuser=req.user).count()
        return render(req, 'Foodapp/index.html', {'success': 'order has been placed', 'count': count})
    except Exception as e:
        return render(req, 'Foodapp/cart.html', {'msg': 'some error'+str(e)})


def showOrders(req):
    osobj = OrderSummery1.objects.filter(customer=req.user)
    oslist = list(osobj)
    print('OS LIST PRINTING')
    print(oslist)
    data = []
    for i in oslist:
        print('///////////////////', i)
        print(i.totalamount)
        q = Orders.objects.filter(ordersobj=i)
        for ordersobj in list(q):
            data.append(ordersobj)
    print(data)
    print('HELLO WORLD')
    count = Cart.objects.filter(currentuser=req.user).count()

    return render(req, 'Foodapp/myorder.html', {'data': oslist, 'data1': data, 'count': count})


def showallorders(req):
    data = OrderSummery1.objects.all()
    count = Cart.objects.filter(currentuser=req.user).count()

    return render(req, 'Foodapp/allorder.html', {'data': data, 'count': count})

# ///////////////////////////////////////////////////////////////////////////////////////////////////////////


def graph(req):
    fcount = Food.objects.all().count()
    ccount = User.objects.all(). count()
    ocount = OrderSummery1.objects.all().count()
    amount = list(OrderSummery1.objects.values_list('totalamount'))
    totalamount = 0
    for i in amount:
        totalamount += i[0]
    print(fcount, ccount, ocount, totalamount)
    return render(req, 'Foodapp/graph.html', {'fcount': fcount, 'ccount': ccount, 'ocount': ocount, 'total': totalamount})


def cgraph(req):
    data1 = OrderSummery1.objects.all()
    data = read_frame(data1)
    print(data, type(data))
    cust = data.groupby('customer')['id'].count()
    print(cust, type(cust))
    plt.plot(cust.index, cust.values)
    plt.show()
    return render(req, 'Foodapp/graph.html')


def categorygraph(req):

templates/Foodapp/addfood.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add Food</title>
</head>
<body>
    <div>
        
    </div>
    <form align="center" method="post" enctype="multipart/form-data">
        {% csrf_token %}

        {{form.as_p}}
        <input type="submit" value="submit">
    
    </form>
</body>
</html>

templates/Foodapp/allorder.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>hello</h1>
    {% for data in data %}
    
    
    
    <table style="width:50%">
        <thead>
            <tr>
                <td>Customer</td>
                <td>Total amount</td>
                
            </tr>
            <tbody>
                <tr>
                    <td>{{data.customer}}</td>
                    <td>{{data.totalamount}}</td>
                 
                </tr>
            </tbody>
        </thead>
        {% endfor %}
    </table>

templates/Foodapp/cart.html
<!DOCTYPE html>
<html>
<head>
    <title>web page</title>
<style>
table{
  font-family: Arial, Helvetica, sans-serif;
  border-collapse: collapse;
  width: 100%;
  margin: 10px 0px;
}

td, #customers th {
  border: 1px solid #ddd;
  padding: 8px;
}

tr:nth-child(even){background-color: #f2f2f2;}

tr:hover {background-color: #ddd;}

th {
  padding-top: 12px;
  padding-bottom: 12px;
  text-align: left;
  background-color: #04AA6D;
  color: white;
}
</style>
</head>
<body>
    {% include 'foodapp/header.html' %}
<form action="/addorders/" method="POST" align="center" enctype="multipart/form-data">
{% csrf_token %}
<table border="2px" width="90%" cellpadding="5px" cellspacing="0px">

<tr>
    <th>Food</th>
    <th>Per Price</th>
    <th>Quantity</th>
    <th>Total</th>
    <th>Action</th>
</tr>
{% for item in cart %}
<tr>
    <td>
    <label>{{item.fid.name}}</label><br>
    <img src="{{item.fid.image.url}}" alt="img" height="150" width="150">
    </td>
    <td><label id='price{{item.id}}'>{{item.fid.price}}</label></td>
    <td><input type="number" data-itemId={{item.id}} name="itemquantity" min='1' value="{{item.itemquantity}}" class="qnt"></td>
    <td><input type="text" name="total" value="{{item.total}}" id="cost{{item.id}}" class="total" readonly ></td>
    <td>{% if perms.foodapp.delete_cart %}
        <a href="/deletecart/{{item.id}}">Delete</a>
        {% endif %}
    </td>
</tr>
{% endfor %}
</table>
<div>
    <label>total amount</label>
    <input type="text" id="totalamount" name="totalbill" value='0' readonly>
    <input type="submit" value="order place">
</div>

</form>
{% include 'foodapp/footer.html' %}
<script>
$(document).ready(function(){
    
    $(".qnt").change(function(){
        calculatetotal(this);
    })
});
function calculatetotal(ctrl)
{
    var quantity=Number($(ctrl).val());
    id=$(ctrl).attr('data-itemId');
    perprice=$('#price'+id).html();
    update(quantity,perprice,id);
}
function update(quantity,perprice,id)
{
    $.ajax({
    url:'/updatecart/',
    method:'POST',
    async:true,
    cache:false,
    data:{'q':quantity,'csrfmiddlewaretoken':'{{csrf_token}}','id':id,'p':perprice},
    success:function(response)
    {
        console.log(response);
        $('#cost'+id).val(response.amount);
        $('#totalamount').val(response.bill);

    },
    error:function()
    {

    }
    });
}

</script>
</body>
</html>

templates/Foodapp/customer.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% for cust in data %}
    
    
    
    <table style="width:50%">
        <thead>
            <tr>
                <td>Email</td>
                <td>Location</td>
                <td>Number</td>
                <td>First Name</td>
                <td>Last Name</td>
            </tr>
            <tbody>
                <tr>
                    <td>{{cust.user.email}}</td>
                    <td>{{cust.location}}</td>
                    <td>{{cust.number}}</td>
                    <td>{{cust.user.first_name}}</td>
                    <td>{{cust.user.last_name}}</td>
                </tr>
            </tbody>
        </thead>
        {% endfor %}
    </table>






</body>
</html>

templates/Foodapp/footer.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body><footer>
        <p>Powered by
        <a href="#" target="_blank">Js Technology Solutions</a>
        | &copy; 2021, All rights reserved </p>
    </footer>
</body>
</html>

templates/Foodapp/header.html
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css"/>
<link href="//netdna.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.css" rel="stylesheet" />
{% load static %}
<!-- <script scr="{% static 'js/jquery.min.js' %}"></script> -->
<script
  src="https://code.jquery.com/jquery-3.6.0.min.js"
  integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
  crossorigin="anonymous"></script>
<style>
footer {
    width: 100%;
    height: 50px;
    background-color: #2d75ff;
    color: #fff;
    bottom: 0;
    padding: 15px;
    text-align: center;
    position:absolute;
}
    footer a, footer a:hover, footer a:focus {
        color: #b1d5f5;
    }
header {
    border-bottom: 1px solid #b5b1b1;    
}
.popcart {
    color: darkblue;    
    background-color: white;
    border: 1px solid darkblue;
    margin-top: -4px;
    margin-left: -13px;
    height: 23px;
}
header .navbar{
    border-radius:0;
    background-color:#fff;
    color:black;
    border:none;
    padding:15px 0 0 15px;
}
.container-fluid{
    padding:0;
}
.navbar-header {
    border-right: 1px solid #b5b1b1;
    height:60px;
}
.navbar-header img {
    width: 150px;    
}
header .header-content {
    padding-left: 50px;
    color: #687080;
    width:100%;
    display:flex;
}
.searchbox{
    width:370px;
    display:flex;
}
.searchicon {
    font-size: 1em;
    margin-top: 17px;
    margin-left: -25px;
    cursor: pointer;
}
    header .user-info {
        /*width: 20%;*/
        text-align: center;
        height:60px;
        /*right: 0;
        position: absolute;*/
        padding-top: 15px;
        border-left: 1px solid #b5b1b1;
    }
header .cart {
    text-align: center;
    height: 60px;
    padding-top: 5px;
    border-left: 1px solid #b5b1b1;
    display:flex;
    padding-left:35px;
}
header .cart a{
font-size:2em;
}
    header .user-info span.short-name {
        padding:10px;
        width: 30px;
        height: 30px;
        border-radius: 20px;
        background-color: darkblue;
        color: #fff;
        font-weight: bold;
    }
    header .user-info span.full-name {
        margin-top:10px;
    }
.menu{
    width:100%;
    padding:10px;    
}
ul.menu {
    list-style-type: none;
    display: flex;
    margin-left:-50px;
}
    ul.menu a, .cart a{
        text-decoration: none;
        color: darkblue;
    }
    ul.menu a:active, ul.menu a:visited {
        color: darkblue;
    }
    ul.menu li {
        color:darkblue;
        min-width:60px;
        font-size:1.2em;
        padding:5px 0 0 10px;
        list-style-type:none;
    }
    ul.menu li:hover {
        background-color: #f5f9ff;
    }
    ul.menu li ul.submenu{
        display:none;
    }
</style>
</head>
<body>
 <header>
        <div class="container-fluid">
            <div class="navbar">
                <div class="col-sm-2">
                    <div class="navbar-header">
                        <img src="{% static 'images/LOGO-FOODPLAZAa1.jpg'%}" alt="logo" />
                    </div>
                </div>
                <div class="col-sm-7">
                    <div class="header-content">
                        <ul class="menu">
                            <li><a href="/showfood">Food</a></li>
                            <li><a href="/showfood">Special</a></li>
                            <li><a href="/showfood">Veg</a></li>
                            <li><a href="/showfood">Non-Veg</a></li>

                            {% if perms.Foodapp.add_food %}
                            <li><a href="/showuser">Customers</a></li>
                            <li><a href="/graph">Graphs</a></li>
                            <li><a href="/addfood">Add Food</a></li>
                            <li><a href="/showalluser">Orders</a></li>
                            {% endif %}

                            {% if perms.Foodapp.view_food or perms.Foodapp.add_cart %}
                            <li><a href="/profile">Profile</a></li>
                            {% endif %}

                            {% if perms.Foodapp.add_cart %}
                            <li><a href="/cart">My Cart</a></li>
                            <li><a href="/showorders/">My Orders</a></li>
                            {% endif %}

                            <!-- <li><a href="/logout">logout</a></li> -->
                        </ul>

                    </div>
                </div>
                <div class="col-sm-1">
                    <div class="cart">
                        <a href="/cart"><span class="fa fa-shopping-cart"></span></a>
                        <span class="badge popcart">{{count}}</span>
                    </div>
                </div>
                <div class="col-sm-2">
                    <div class="user-info">
                        {% if request.user.is_authenticated  %}
                        <span class="short-name">JS</span>
                        <span class="full-name">{{ request.user}}</span>
                        <span><a href="/logout">logout</a></span>

                        {%  else %}
                        <span><a  href="/login">Login</a> | </span>
                        <span><a href="/signup">Sign Up</a></span>
                        {% endif %}
                    </div>
                    <div class="user-menus">

                    </div>
                </div>
            </div>
        </div>        
    </header>

templates/Foodapp/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% include 'Foodapp/header.html' %}
    {% include 'Foodapp/footer.html' %}
    
</body>
</html>

templates/Foodapp/menu.html
 <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Show food</title>
    <style>
        .success{
            position: fixed;
            padding: 10px;
            font-weight: bold;
            font-size: 25px;
            height: 50px;
            color:red;
            border: 5px solid #e60000;
            background-color: pink;
        }

        .error{
            top:0;
            padding: 10px;
            border: 5px solid #e60000;
            background-color: #ffb3b3;
            font-weight: bold;
            height: 50px;
            max-width: 200px;
            text-align: center;
        }




    </style>
</head>
<body>
    {% include 'Foodapp/header.html' %}
    <div id="msg"> </div>
    <form method='POST' align='center' enctype="multipart/form-data">
   
    {% csrf_token %}
    <table id="tbItems" class="table table-hover" width="100%" cellspacing="0">
        <thead>
            <tr>
                <th>Name</th>
                <th>Price</th>
                <th>Quantity</th>
                <th>Types</th>
                <th>Category</th>
                <th>Image</th>
                <th>Action</th>
            </tr>
        </thead>
            {% for f in food %}
        
        <tbody>
            <tr>
                <td>{{f.name}}</td>
                <td id="price">{{f.price}}</td>
                <td>{{f.quantity}}</td>
                <td>{{f.types}}</td>
                <td>{{f.category}}</td>
                <td><img src="{{f.image.url}}" alt="img" height="120" width="140"></td>

            <td>
                {% if perms.Foodapp.change_food %}
                <a href="/updatefood/{{f.id}}">Edit</a>
                <a href="/deletefood/{{f.id}}">Delete</a>
                {% endif %}
                {% if perms.Foodapp.view_cart %}
                {% if f.id not in cartdata %}
                <a href="#" class="addtocart btn btn-primary" id="{{f.id}}">Add to cart</a>
                {% else %}
                <a href="/cart" class="btn btn-primary">Go to Cart</a>
                {% endif %}
                {% endif %}
            </td>

            </tr>
        </tbody>


        {% endfor %}

    </table>
    
</form>
{% include 'Foodapp/footer.html' %}
<script>
    $(document).ready(function(){
        $('.addtocart').click(function(){
            $.ajax({
                url:'/addtocart',
                method:'GET',
                cache:false,
                data:{'foodid':$(this).attr("id")},
                success:
                function()
                {
                    $('#msg').html('item has been added');
                    $('#msg').addClass('success').fadeOut(5000);
                    $('#msg').removeClass('error');

                },
                error:
                function()
                {
                    $('#msg').html('some error occured');
                    $('#msg').addClass('error')
                    $('#msg').removeClass('successs');
                }
            });
        });
    });
</script>
</body>

</html> 

templates/Foodapp/sample.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h3>hello world</h3>
</body>
</html>